### ISSUE TITLE
不支持session吗？为什么我输入请继续，就不知道了，官网可是会继续接上下文回答

### ISSUE THREAD

**Issue by stevenrao** [869413421/chatgpt-web#10]

**Comment by gygy** [comment]
测试是支持的

**Comment by stevenrao** [comment]
![image](https://user-images.githubusercontent.com/6369621/219260448-07921101-d26d-4dc5-8fe5-f935d7a0077c.png)
不支持啊, 这是chatgpt-web搭建的。问继续不知道我问什么。
![image](https://user-images.githubusercontent.com/6369621/219261004-8f3ae0d0-8377-4559-883a-efa0206c06d4.png)
这是官方的。

**Comment by 869413421** [comment]
项目是基于gpt3.0api实现，效果是和chatgpt有区别的。
