### ISSUE TITLE
Windows端打开页面还是显示空白

### ISSUE THREAD

**Issue by xzl0326** [869413421/chatgpt-web#100]
Windows端的exe程序开启，浏览器打开还是显示一片空白。控制台只显示了一个
        
 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.    index-dc745692.js:1 

命令行里就是GET “/”

**Comment by 869413421** [comment]
> Windows端的exe程序开启，浏览器打开还是显示一片空白。控制台只显示了一个
> 
> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec. index-dc745692.js:1
> 
> 命令行里就是GET “/”
我这里无法重现这个问题，只能尝试优化修复。

**Comment by xzl0326** [comment]
好的

**Comment by xzl0326** [comment]
可以了
