### ISSUE TITLE
登录页面

### ISSUE THREAD

**Issue by Zzzzz-L** [869413421/chatgpt-web#104]
为什么我账号密码设置为空，还有登录页面？

**Comment by imsprojo2fan** [comment]
随便设个账号密码就能登录

**Comment by Zzzzz-L** [comment]
这样的话我们二次开发需要带Authorization了应该，有没有办法去掉这个认证呀

**Comment by imsprojo2fan** [comment]
> 这样的话我们二次开发需要带Authorization了应该，有没有办法去掉这个认证呀

web.go里改路由

**Comment by Zzzzz-L** [comment]
好的，谢谢您

**Comment by 869413421** [comment]
增加jwt的目的是为了保证安全性，如果没有登录功能这个项目部署在外网，很容易被人扒取接口盗用key。如果你不需要，可以自己动手去掉。只要将router. go里面的jwt中间件去掉即可。
