### ISSUE TITLE
采用nginx反代并开启auth_basic验证后nginx反复要求验证或者登陆界面不工作

### ISSUE THREAD

**Issue by lainme** [869413421/chatgpt-web#105]
按照readme的配置方法启用nginx反代并开启了auth_basic验证，路径是/。

如果用chrome，nginx会反复弹出验证窗口（确定用户名密码是正确的）。如果用Firefox，nginx虽然不会反复弹窗，但登陆界面输入用户名密码后（确定用户名密码是正确的），要么仍然回到登陆界面（但用户名密码栏清空），要么提示用户名密码错误。

关掉nginx的auth_basic可以正常登陆。chatgpt-web版本0.2.1, nginx版本1.14.2。

**Comment by 869413421** [comment]
> 按照readme的配置方法启用nginx反代并开启了auth_basic验证，路径是/。
> 
> 如果用chrome，nginx会反复弹出验证窗口（确定用户名密码是正确的）。如果用Firefox，nginx虽然不会反复弹窗，但登陆界面输入用户名密码后（确定用户名密码是正确的），要么仍然回到登陆界面（但用户名密码栏清空），要么提示用户名密码错误。
> 
> 关掉nginx的auth_basic可以正常登陆。chatgpt-web版本0.2.1, nginx版本1.14.2。

新版本已经增加了登录认证，没必要再使用nginx认证了。
