### ISSUE TITLE
登录进去，用户名和密码是多少？

### ISSUE THREAD

**Issue by wangchangquan** [869413421/chatgpt-web#110]

**Comment by liyongempire** [comment]
这个可以自行添加，在config.json   "auth_user": "账号",
  "auth_password": "密码" 改成需要的就可以了

**Comment by herotangabc** [comment]
用户名添加了也不好使，添加个用户aaa,密码bbb,用aaa和bbb 登陆不进去

**Comment by dragonrainy** [comment]
我也遇到了同样的问题，添加了之后也还是登录不进去，显示账号密码错误

**Comment by guolin** [comment]
我也是

**Comment by wangchangquan** [comment]
添加账号 密码，解决了。
 "auth_user": "账号",
"auth_password": "密码"
