### ISSUE TITLE
局域网访问空白，本机访问正常。

### ISSUE THREAD

**Issue by liyongempire** [869413421/chatgpt-web#111]
[GIN-debug] GET    /assets/:filename         --> github.com/869413421/chatgpt-web/bootstarp.initStaticServer.func1 (4 handlers)
[GIN-debug] GET    /logo192.png              --> github.com/gin-gonic/gin.(*RouterGroup).StaticFile.func1 (4 handlers)
[GIN-debug] HEAD   /logo192.png              --> github.com/gin-gonic/gin.(*RouterGroup).StaticFile.func1 (4 handlers)
[GIN-debug] GET    /logo512.png              --> github.com/gin-gonic/gin.(*RouterGroup).StaticFile.func1 (4 handlers)
[GIN-debug] HEAD   /logo512.png              --> github.com/gin-gonic/gin.(*RouterGroup).StaticFile.func1 (4 handlers)
[GIN-debug] GET    /favicon.ico              --> github.com/gin-gonic/gin.(*RouterGroup).StaticFile.func1 (4 handlers)
[GIN-debug] HEAD   /favicon.ico              --> github.com/gin-gonic/gin.(*RouterGroup).StaticFile.func1 (4 handlers)
[GIN-debug] GET    /manifest.json            --> github.com/gin-gonic/gin.(*RouterGroup).StaticFile.func1 (4 handlers)
[GIN-debug] HEAD   /manifest.json            --> github.com/gin-gonic/gin.(*RouterGroup).StaticFile.func1 (4 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8080
[GIN] 2023/03/31 - 09:10:31 |[97;42m 200 [0m|      2.6972ms |     192.168.3.3 |[97;44m GET     [0m "/"
[GIN] 2023/03/31 - 09:10:46 |[97;42m 200 [0m|      2.0305ms |     192.168.3.3 |[97;44m GET     [0m "/"
[GIN] 2023/03/31 - 09:11:29 |[97;42m 200 [0m|      1.3984ms |     192.168.3.8 |[97;44m GET     [0m "/"
[GIN] 2023/03/31 - 09:11:29 |[97;42m 204 [0m|            0s |             ::1 |[90;47m OPTIONS [0m "/auth/info"
[GIN] 2023/03/31 - 09:11:29 |[97;42m 200 [0m|       950.4µs |             ::1 |[97;46m POST    [0m "/auth/info"
[GIN] 2023/03/31 - 09:11:30 |[97;42m 200 [0m|    190.1758ms |     192.168.3.8 |[97;44m GET     [0m "/favicon.ico"
[GIN] 2023/03/31 - 09:11:35 |[97;42m 200 [0m|       949.3µs |     192.168.3.3 |[97;44m GET     [0m "/"
[GIN] 2023/03/31 - 09:11:35 |[97;42m 200 [0m|       154.8µs |     192.168.3.3 |[97;44m GET     [0m "/favicon.ico"

**Comment by liyongempire** [comment]
windows端，本机可以正常访问，局域网其他电脑不能，显示空白。防火墙出站和入站都有允许

**Comment by 869413421** [comment]
浏览器控制台错误信息有吗？提供一下。

**Comment by fankoo** [comment]
auth 503

**Comment by liyongempire** [comment]
![企业微信截图_16803415838388](https://user-images.githubusercontent.com/71498336/229278204-fa79e008-d57f-43a9-91fe-1e8259fa5764.png)

**Comment by liyongempire** [comment]
新版本已经修复了，完结
