### ISSUE TITLE
gpt-4使用报错

### ISSUE THREAD

**Issue by detectRecog** [869413421/chatgpt-web#113]
使用最新的chatgpt-web-v0.2.4-linux-amd64.tar.gz，代理也搭好了
解压后使用默认的“gpt-3.5-turbo-0301”，聊天没有问题，也没有报错。

将model改为了gpt-4后，
报错如图，错误信息为：error, status code:404, message: `gpt-4` does not exist

**Comment by detectRecog** [comment]
报错图片访问方法：链接: https://pan.baidu.com/s/1V5y5dzdmjRiWBuGDr8kfwg 提取码: 170t
json文件内容：
```

{
  "api_key": "sk-xxx",
  "api_url": "",
  "port": 8080,
  "listen": "",
  "bot_desc": "你是一个AI助手，我需要你模拟一名温柔贴心的女朋友来回答我的问题。",
  "proxy": "http://127.0.0.1:7890",
  "model": "gpt-4",
  "max_tokens": 512,
  "temperature": 0.9,
  "top_p": 1,
  "frequency_penalty": 0.0,
  "presence_penalty": 0.6,
  "auth_user": "xxx",
  "auth_password": "xxx"
}
```

**Comment by 869413421** [comment]
需要申请通过后才能使用，项目不支持token的方式。
