### ISSUE TITLE
go: module cache not found: neither GOMODCACHE nor GOPATH is set

### ISSUE THREAD

**Issue by siqin-ai** [869413421/chatgpt-web#114]
我在宝塔里启动GO项目，启动失败呢，各位大佬调教一下

**Comment by siqin-ai** [comment]
go: module cache not found: neither GOMODCACHE nor GOPATH is set

**Comment by siqin-ai** [comment]
![db26c09d215392bfc2cc60cb193a22d](https://user-images.githubusercontent.com/79462124/229279146-80964b27-489d-4c71-bf8e-a74a75059a5f.png)

**Comment by 869413421** [comment]
开启go module并且配置go代理，详情请自行百度。
