### ISSUE TITLE
修改config中的auth_password不生效

### ISSUE THREAD

**Issue by HappyTsing** [869413421/chatgpt-web#126]

**Comment by mike22437120** [comment]
重启机器或者用命令杀进城 killall -9 go 然后再重新启动

**Comment by JieGuo1025** [comment]
在config.json中账户密码默认为空，登陆不进去，设置了账户和密码 也登陆不进去，WHY？

**Comment by 869413421** [comment]
> 在config.json中账户密码默认为空，登陆不进去，设置了账户和密码 也登陆不进去，WHY？

设置用户名后重启程序。
