### ISSUE TITLE
如何把模型设置为gpt4

### ISSUE THREAD

**Issue by JieGuo1025** [869413421/chatgpt-web#127]
config.json中目前model的值为gpt-3.5-turbo-0301，我想把模型改为gpt-4，我目前试过把值改成gpt-4，且使用的API-KEY是plus账号里面生成的，但是似乎不行。那么该如何设置，需要什么前置条件，在前置条件满足后，如何配置

**Comment by 869413421** [comment]
> config.json中目前model的值为gpt-3.5-turbo-0301，我想把模型改为gpt-4，我目前试过把值改成gpt-4，且使用的API-KEY是plus账号里面生成的，但是似乎不行。那么该如何设置，需要什么前置条件，在前置条件满足后，如何配置

需要在官网申请gpt4的api，通过后才能使用。

**Comment by JieGuo1025** [comment]
> 

感谢耐心解答

**Comment by JieGuo1025** [comment]
> > config.json中目前model的值为gpt-3.5-turbo-0301，我想把模型改为gpt-4，我目前试过把值改成gpt-4，且使用的API-KEY是plus账号里面生成的，但是似乎不行。那么该如何设置，需要什么前置条件，在前置条件满足后，如何配置
> 
> 需要在官网申请gpt4的api，通过后才能使用。

谢谢解答
