### ISSUE TITLE
请求错误，error，status code:500

### ISSUE THREAD

**Issue by linfeng-xie** [869413421/chatgpt-web#14]
突然就请求错误，error，status code:500了，上两天还是可以用的

**Comment by infoBrainSys** [comment]
同问

**Comment by soopper** [comment]
同问

**Comment by Yohansun** [comment]
好像是chatGPT本身有问题了

**Comment by Yohansun** [comment]
> 突然就请求错误，error，status code:500了，上两天还是可以用的

我靠，还没好，是咋回事

**Comment by 869413421** [comment]
昨天openai接口挂了。

**Comment by 869413421** [comment]
> > 突然就请求错误，error，status code:500了，上两天还是可以用的
> 
> 我靠，还没好，是咋回事

现在应该已经恢复。
