### ISSUE TITLE
感觉问题回答不全，中间断了

### ISSUE THREAD

**Issue by hahau6** [869413421/chatgpt-web#15]
感觉问题回答不全，中间断了
![捕获](https://user-images.githubusercontent.com/105804300/221138408-c5e9910b-7cc4-43a5-84b9-9d081184e803.PNG)
![无标题1](https://user-images.githubusercontent.com/105804300/221138418-7d0848d1-d0c6-4c31-8aa1-367968cb6065.png)

**Comment by 869413421** [comment]
接口响应tokens长度限制了，如需回复更多内容请修改配置文件中max_tokens选项。
