### ISSUE TITLE
被墙了？

### ISSUE THREAD

**Issue by yizhixiaoshagua** [869413421/chatgpt-web#21]
"Post \"https://api.openai.com/v1/chat/completions\": dial tcp 157.240.8.50:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
国内IP挨墙了？

**Comment by richsamer** [comment]
Seems like the API is blocked

**Comment by 869413421** [comment]
y

**Comment by Mydingyan** [comment]
昨天才部署，今天就被墙了

**Comment by xiandan-erizo** [comment]
+1

**Comment by shijinyana** [comment]
确实被墙了

**Comment by 869413421** [comment]
已添加代理配置，请阅读readme.

**Comment by shijinyana** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
