### ISSUE TITLE
不会用，求教

### ISSUE THREAD

**Issue by DannyJRu** [869413421/chatgpt-web#24]
我的win10，下载的[chatgpt-web-v0.0.4-windows-amd64.zip]按照说明进行了配置，结果双击exe后弹出如下提示
 [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.

**Comment by 869413421** [comment]
启动成功了，打开本地8080端口即可。
