### ISSUE TITLE
/v1/chat/completions 404

### ISSUE THREAD

**Issue by xin800** [869413421/chatgpt-web#25]
方便帮忙看看什么原因?
![image](https://user-images.githubusercontent.com/9602020/222729622-b43484fb-8733-4c2a-9cc3-5efe9a3599ef.png)

**Comment by SizheRee** [comment]
同问，应该是代理的问题，能不能在请求前弄一个http代理

**Comment by 869413421** [comment]
猜测这个应该是openai的问题，代理请求到请求的服务器没更新这个接口？

**Comment by 869413421** [comment]
暂时没有在我机器上复现到这个问题，尝试切换代理试下。

**Comment by 869413421** [comment]
> 同问，应该是代理的问题，能不能在请求前弄一个http代理

已添加到项目中，请使用用最新代码和镜像。
