### ISSUE TITLE
"bot-desc"参数设定的问题

### ISSUE THREAD

**Issue by ztdexter** [869413421/chatgpt-web#27]
非常感谢作者，这个项目，一下子让操作方便多了。
我是小白，只会依照步骤操作，有点疑问，想请教一下大家。
如果设定了语法标准英语类角色，是不是在其他方面的回答就会弱一点？有些专业领域的问题是不是需要来回切换一下角色？
一般性事务的话，是不是基本不用专门调整参数了吧？默认即可解决大多数情况了。
两个疑惑，
1、后期有时间会在清空对话旁边有简易的ai 切换 比如： 软件工程师，修改润色，问题回答，之类的按钮切换？
2、Windows的这个dos窗口能否后台运行，不在任务栏出现。
非常感谢。

**Comment by 869413421** [comment]
> 非常感谢作者，这个项目，一下子让操作方便多了。
> 我是小白，只会依照步骤操作，有点疑问，想请教一下大家。
> 如果设定了语法标准英语类角色，是不是在其他方面的回答就会弱一点？有些专业领域的问题是不是需要来回切换一下角色？
> 一般性事务的话，是不是基本不用专门调整参数了吧？默认即可解决大多数情况了。
> 两个疑惑，
> 1、后期有时间会在清空对话旁边有简易的ai 切换 比如： 软件工程师，修改润色，问题回答，之类的按钮切换？
> 2、Windows的这个dos窗口能否后台运行，不在任务栏出现。
> 非常感谢。

并不会，设定只会影响回答方式。实际上处理问题的能力依然一样。
