### ISSUE TITLE
返回 “请求出错，undefined”

### ISSUE THREAD

**Issue by L0yy** [869413421/chatgpt-web#28]
环境：
1. 拉取的 docker hub 下的later版本
2. 服务器是美国的
3. 启动命令参考自
  > https://github.com/869413421/chatgpt-web#%E4%BD%BF%E7%94%A8docker%E8%BF%90%E8%A1%8C 第二种方式启动
4. 配置如下：
``` 
{
  "api_key": "sk-uxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "port": 8080,
  "bot_desc": "以下是与AI助手的对话。助手乐于助人，富有创造力，聪明且非常友好",
  "model": "gpt-3.5-turbo-0301",
  "max_tokens": 512,
  "temperature": 0.8,
  "top_p": 1,
  "frequency_penalty": 0.0,
  "presence_penalty": 0.6
}

```
报错如下：
![image](https://user-images.githubusercontent.com/43272685/222877539-c98dd030-ff39-4c52-a5a2-040a2d473814.png)

**Comment by Goforfreedom** [comment]
vps上试一下curl chat.openai.com 
看看返回有没有error code:1020错误，如有，证明VPS ip不行，套个cfvwarp

**Comment by L0yy** [comment]
确实vps的IP不行，换了个IP可用了
之前的返回结果
```
ubuntu@VM-166-41-ubuntu:~$ curl chat.openai.com
curl: (7) Failed to connect to chat.openai.com port 80: Connection timed out
```
