### ISSUE TITLE
连接出错，经常跳换IP地址，都是失败？

### ISSUE THREAD

**Issue by ztdexter** [869413421/chatgpt-web#29]
连接出错，直接上chatgpt是ok，但是就是用这个显示连接错误，里面的IP地址也会跳成别的。
我设定全局也不行。 应该不是key的问题吧。
![334244223424](https://user-images.githubusercontent.com/9154388/222878186-40a6b335-c8da-45fc-86e2-57fad18f6dea.png)

**Comment by 869413421** [comment]
墙了，后续更新会加上请求代理。

**Comment by 869413421** [comment]
已添加代理配置
