### ISSUE TITLE
欢迎词能修改吗

### ISSUE THREAD

**Issue by yanquan2020** [869413421/chatgpt-web#3]
如题

**Comment by yanquan2020** [comment]
> 如题

改"bot_desc"好像也没用

**Comment by gygy** [comment]
+1

**Comment by 869413421** [comment]
> > 如题
> 
> 改"bot_desc"好像也没用

请参考官网示例文档

**Comment by 869413421** [comment]
可自行fork代码修改，前端代码在chat目录下。修改编译静态文件后替换到static目录和resource目录。

**Comment by yanquan2020** [comment]
> 可自行fork代码修改，前端代码在chat目录下。修改编译静态文件后替换到static目录和resource目录。

是自己在go环境下重新修改编译吗？

**Comment by feko2018** [comment]
可以，js那里，你按f12看下哪个js文件 做了Unicode转换的

**Comment by KevinJun2017** [comment]
求详细步骤

**Comment by yongqi78** [comment]
在chat路径下 npm run build，生成静态文件（build文件夹），将chat里面的static文件夹替换项目的static文件，将build文件夹里的index.html替换resources\view\index.html文件
