### ISSUE TITLE
我是使用您的dokcer版，提问最近世界的大赛，它的回答是2021年，而我其他基于3.0的模型，回答则是2023年的

### ISSUE THREAD

**Issue by dmuxue** [869413421/chatgpt-web#31]
我是使用您的dokcer版，提问最近世界的大赛，它的回答是2021年，而我其他基于3.0的模型，回答则是2023年的

**Comment by 869413421** [comment]
> 我是使用您的dokcer版，提问最近世界的大赛，它的回答是2021年，而我其他基于3.0的模型，回答则是2023年的

回答是有随机性的，chatgpt只是一个语言模型，你要知道它给出的回答并不一定是有事实依据的。
