### ISSUE TITLE
如何使用代理呢？

### ISSUE THREAD

**Issue by mormiddle** [869413421/chatgpt-web#32]
需要自己创建反代吗？如果需要的话，如何填入反代呢？

**Comment by 869413421** [comment]
在配置文件中修改proxy参数即可。

**Comment by 869413421** [comment]
容器中使用http://host.docker.internal:10809，10809修改为宿主机代理端口。

**Comment by mormiddle** [comment]
感谢大佬，我去试试

**Comment by leexuan** [comment]
代理是在容器中设置，还是在宿主机设置呢？有更具体的说明吗？

**Comment by 869413421** [comment]
> 代理是在容器中设置，还是在宿主机设置呢？有更具体的说明吗？

代理是指你宿主机的代理，容器内通过宿主机向OPENAI发起请求。

**Comment by shijinyana** [comment]
大佬我想形容下 情况  感觉有点抓瞎
 新增的配置中多了一个 proxy 属性  应该怎么填写
  目前是我有两个电脑  一个是软件在上面运行 一个是通过软件进行了 翻墙   我填入ip 但是port 应该怎么填写的 有没有详细解释的 大佬

**Comment by zl-research** [comment]
> 容器中使用[http://host.docker.internal:10809，10809修改为宿主机代理端口。](http://host.docker.internal:10809%EF%BC%8C10809%E4%BF%AE%E6%94%B9%E4%B8%BA%E5%AE%BF%E4%B8%BB%E6%9C%BA%E4%BB%A3%E7%90%86%E7%AB%AF%E5%8F%A3%E3%80%82)

大佬，proxy写的是http://127.0.0.1:10809，浏览器访问时出现：proxyconnection tcp:dial tcp 127.0.0.1:62245 connectex no connection could be made because the target machine actively refused it.。这个应该怎么解决

**Comment by 869413421** [comment]
> 大佬我想形容下 情况  感觉有点抓瞎
>  新增的配置中多了一个 proxy 属性  应该怎么填写
>   目前是我有两个电脑  一个是软件在上面运行 一个是通过软件进行了 翻墙   我填入ip 但是port 应该怎么填写的 有没有详细解释的 大佬

要用翻墙电脑的公网ip和使用翻墙软件的端口

**Comment by shijinyana** [comment]
ok 谢谢大佬的解惑  非常感谢 已经搞定了

**Comment by Johntang666** [comment]
> > 大佬我想形容下 情况  感觉有点抓瞎
> > 新增的配置中多了一个 proxy 属性  应该怎么填写
> > 目前是我有两个电脑  一个是软件在上面运行 一个是通过软件进行了 翻墙   我填入ip 但是port 应该怎么填写的 有没有详细解释的 大佬
> 
> 要用翻墙电脑的公网ip和使用翻墙软件的端口

翻墙电脑的公网ip是不是就是在浏览器输入ip后的那个地址，然后我使用这个公网ip和软件提供的http端口，就会报拒绝连接的错误
