### ISSUE TITLE
An error occurred in the request

### ISSUE THREAD

**Issue by PWMFI** [869413421/chatgpt-web#35]
An error occurred in the request，Post "https://api.openai.com/v1/chat/completions": proxyconnect tcp: dial tcp 127.0.0.1:10809: connectex: No connection could be made because the target machine actively refused it.

**Comment by PWMFI** [comment]
How do I modify the proxy for this

**Comment by 869413421** [comment]
Modify the config file proxy configuration

**Comment by PWMFI** [comment]
How do I fill in the correct parameters and how do I create an agent?

**Comment by HelloMorningStar** [comment]
Don't fill in anything, like this：

 "proxy": "",

**Comment by bitten-littlesuqirrel** [comment]
so am i
how to fix it？

**Comment by bitten-littlesuqirrel** [comment]
> Don't fill in anything, like this：
> 
> "proxy": "",

the same error came out when i move 'http://127.0.0.1:8080/' away from proxy

**Comment by PWMFI** [comment]
Is there any workaround

**Comment by 869413421** [comment]
With the latest version, no proxy is used by default.

**Comment by lin65505578** [comment]
默认不行啊
 dial tcp 31.13.94.7:443: connectex: A connection attempt failed
