### ISSUE TITLE
docker pull出错

### ISSUE THREAD

**Issue by frankyzhu76** [869413421/chatgpt-web#36]
docker pull qingshui869413421/chatgpt-web后提示
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'

虽然GO能运行，但是还是习惯用DOCKER，咋办？

**Comment by 869413421** [comment]
测试并没有出现同样的情况，提供下你完整的启动命令？

**Comment by frankyzhu76** [comment]
已解决，是DOCKER的问题，卸载，UPDATA，再装DOCKER就解决了~谢谢~
