### ISSUE TITLE
想问下支持chatGPT的API吗？

### ISSUE THREAD

**Issue by ChenCheng2Cs** [869413421/chatgpt-web#37]
如题

**Comment by 3500024137** [comment]
这就是api啊

**Comment by ChenCheng2Cs** [comment]
> 这就是api啊

不好意思，可能没说清楚。 上个星期应该是出了一个chatGPT的API。 虽然都是基于语言模型 GPT 3.5, 但是那个接口好像是对聊天有做加强。 并且费用要比直接调用GPT模型低十倍，不知道是否能选择掉那个接口

**Comment by 869413421** [comment]
> > 这就是api啊
> 
> 不好意思，可能没说清楚。 上个星期应该是出了一个chatGPT的API。 虽然都是基于语言模型 GPT 3.5, 但是那个接口好像是对聊天有做加强。 并且费用要比直接调用GPT模型低十倍，不知道是否能选择掉那个接口

当前默认就是这个

**Comment by ChenCheng2Cs** [comment]
> > > 这就是api啊
> > 
> > 
> > 不好意思，可能没说清楚。 上个星期应该是出了一个chatGPT的API。 虽然都是基于语言模型 GPT 3.5, 但是那个接口好像是对聊天有做加强。 并且费用要比直接调用GPT模型低十倍，不知道是否能选择掉那个接口
> 
> 当前默认就是这个

好的，谢谢回复
