### ISSUE TITLE
页面空白,页面报错

### ISSUE THREAD

**Issue by 3500024137** [869413421/chatgpt-web#40]
最新window版，点进页面后空白

**Comment by 869413421** [comment]
查看控制台日志，看看启动了那个端口。

**Comment by 3500024137** [comment]
> 查看控制台日志，看看启动了那个端口。
使用手机进入也显示空白

**Comment by 3500024137** [comment]
我把你的0.5版本的index.html替换了0.7版本的文件，并更改了读取路径，之后可以显示页面了，但我不确定这是否是正常页面，因为只比之前多了一个复制对话的按钮
![image](https://user-images.githubusercontent.com/53900125/223102269-0dac4d0f-e030-4f81-a88e-3a8d9d1e27fb.png)

**Comment by 3500024137** [comment]
最后我将你的<script type="module" crossorigin src="/assets/index-a80dcab2.js"></script>中的type换成defer之后，页面就正常显示了，不懂啊，这莫名其妙的问题

**Comment by 3500024137** [comment]
最后我将你的<script type="module" crossorigin src="/assets/index-a80dcab2.js"></script>中的type换成defer之后，页面就正常显示了，非常莫名其妙的问题

**Comment by benjaminyzhang** [comment]
同样遇到了该问题

**Comment by 869413421** [comment]
请提供控制台中的信息

**Comment by benjaminyzhang** [comment]
Loading module from “http://127.0.0.1:8080/assets/index-a80dcab2.js” was blocked because of a disallowed MIME type (“text/plain”).
Loading failed for the module with source “http://127.0.0.1:8080/assets/index-a80dcab2.js”.

**Comment by benjaminyzhang** [comment]
index-a80dcab2.js:1 
        
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by 869413421** [comment]
这似乎是一个前端兼容性问题

**Comment by 869413421** [comment]
@rxliuli help

**Comment by rxliuli** [comment]
吾辈测试了 0.0.8 没发现问题，是已经解决了么？

**Comment by 869413421** [comment]
> 吾辈测试了 0.0.8 没发现问题，是已经解决了么？

没有对前端文件做任何改动。😢

**Comment by rxliuli** [comment]
> 最后我将你的 <script type="module" crossorigin src="/assets/index-a80dcab2.js"></script > 中的 type 换成 defer 之后，页面就正常显示了，非常莫名其妙的问题

从这里的解决方法猜测是它的浏览器太旧了不支持 esmodule，或许试试最新的 chrome

**Comment by 3500024137** [comment]
> > 最后我将你的 <script type="module" crossorigin src="/assets/index-a80dcab2.js"></script > 中的 type 换成 defer 之后，页面就正常显示了，非常莫名其妙的问题
> 
> 从这里的解决方法猜测是他的浏览器太旧了不支持 esmodule，或许试试最新的 chrome

不，我的浏览器都是最新的

**Comment by rxliuli** [comment]
1. @869413421 需要服务端修改 mime type ref: https://stackoverflow.com/questions/59908927/failed-to-load-module-script-the-server-responded-with-a-non-javascript-mime-ty
2. 或者修复用户系统注册表中缺失的 Computer\HKEY_CLASSES_ROOT\.js，ref: https://caddy.community/t/failed-to-load-module-script/17408

**Comment by 3500024137** [comment]
新版本好像没啥变化，我依旧是空白
