### ISSUE TITLE
安装在vps上，不需要代理要怎么设置呢？

### ISSUE THREAD

**Issue by jun9100** [869413421/chatgpt-web#41]
安装在vps上，不需要代理要怎么设置呢？
测试了删除代理那一行，但是没有用。

**Comment by 869413421** [comment]
> 安装在vps上，不需要代理要怎么设置呢？
> 测试了删除代理那一行，但是没有用。

docker使用挂载配置文件的方式，将proxy设置为空衣服串。

**Comment by 869413421** [comment]
已更新，最新镜像默认不使用代理。

**Comment by jun9100** [comment]
非常感谢。
