### ISSUE TITLE
极空间docker部署出错，日志如下，请问哪里出了问题呢？

### ISSUE THREAD

**Issue by LYwyc** [869413421/chatgpt-web#43]
![1678085385247](https://user-images.githubusercontent.com/97736099/223038663-2f8fc4aa-a348-469a-8976-e82f0934d38a.png)

**Comment by LYwyc** [comment]
![1678085424873](https://user-images.githubusercontent.com/97736099/223038763-ebe8ae50-ebea-4355-8557-01ad4d4fab31.png)
这是环境配置列表，web页面打不开

**Comment by 869413421** [comment]
删除掉容器镜像，拉取最新的镜像试试，容器内默认启动为8080端口，要确保你映射的端口是正确的。

**Comment by LYwyc** [comment]
> 删除掉容器镜像，拉取最新的镜像试试，容器内默认启动为8080端口，要确保你映射的端口是正确的。

已经重新部署很多次了，端口如上图我改成了3003，因为8080有占用，然后没有做映射因为我没有公网Ipv4，用的host网络，使用公网ipv6访问的

**Comment by LYwyc** [comment]
使用第二种方式配置文件挂载运行成功了，感谢作者
