### ISSUE TITLE
API报错

### ISSUE THREAD

**Issue by Johntang666** [869413421/chatgpt-web#44]
![image](https://user-images.githubusercontent.com/67173358/223043361-97d8a4f3-9e95-47db-aaa2-5cf39950a163.png)
不知道为什么报错这个

**Comment by Johntang666** [comment]
已经改成自己的API-key了，然后出现了这个

**Comment by bitten-littlesuqirrel** [comment]
我也是同样的问题，不管试了哪个版本。还是把proxy参数置空都不行

**Comment by Johntang666** [comment]
> 

这个前面有回复的https://github.com/869413421/chatgpt-web/issues/32#issuecomment-1455430396

**Comment by bitten-littlesuqirrel** [comment]
您链接给的之前尝试过了，还是无法解决。
现在出现的错误和您的一样

**Comment by Johntang666** [comment]
> 您链接给的之前尝试过了，还是无法解决。 现在出现的错误和您的一样

我也是，还没解决

**Comment by 869413421** [comment]
> ![image](https://user-images.githubusercontent.com/67173358/223043361-97d8a4f3-9e95-47db-aaa2-5cf39950a163.png) 不知道为什么报错这个

图中看到已经配置代理到100.100.2.138:53上，请确保代理能正常访问openai。
