### ISSUE TITLE
使用最新版0.0.7出现connection failed问题

### ISSUE THREAD

**Issue by bitten-littlesuqirrel** [869413421/chatgpt-web#45]
<img width="960" alt="8b227ff5a7d19bbd05d05e01bd5f536" src="https://user-images.githubusercontent.com/40733610/223055136-f08eb0b5-a109-41cd-9e4e-864f144d7c2e.png">
在使用最新版之后也会出现这个问题

**Comment by 869413421** [comment]
> <img alt="8b227ff5a7d19bbd05d05e01bd5f536" width="960" src="https://user-images.githubusercontent.com/40733610/223055136-f08eb0b5-a109-41cd-9e4e-864f144d7c2e.png">
> 
> 在使用最新版之后也会出现这个问题

确保配置的代理是正确的，提示中显示你的代理地址没法进行连接。
