### ISSUE TITLE
建议可以自定义API接口

### ISSUE THREAD

**Issue by pd12bbf7608ae1** [869413421/chatgpt-web#47]
项目 https://github.com/dirk1983/chatgpt 中提供了自定义openai接口地址的功能
建议在配置文件中添加类似于 api_endpoint 选项，默认使用 https://api.openai.com/v1/chat/completions ，用户可以自定义该选项，便于使用相关代理。

**Comment by yuqihuang272** [comment]
怎么更新到3.5版本，现在还是版本3的api
