### ISSUE TITLE
401: incorrected api key

### ISSUE THREAD

**Issue by yangyanghoho** [869413421/chatgpt-web#52]
![image](https://user-images.githubusercontent.com/46733715/223409325-baaefc12-9753-4f55-9325-6fd8cff2850e.png)
我用的是最新的0.0.7.
更换过新生成的key也是一样的。
但是用curl试试是没有问题的
curl https://api.openai.com/v1/chat/completions \
>  -H "Authorization: Bearer sk-xxxxxxxx" \
>  -H "Content-Type: application/json" \
>  -d '{
>  "model": "gpt-3.5-turbo",
>  "messages": [{"role": "user", "content": "What is your name?"}] 
>  }'

**Comment by yangyanghoho** [comment]
linux centos上。配置文件如下：
{
  "api_key": "st-xxxxxxx",
  "port": 8081,
  "bot_desc": "You are an AI bot who will answer all my questions.",
  "proxy": "",
  "model": "gpt-3.5-turbo-0301",
  "max_tokens": 512,
  "temperature": 0.9,
  "top_p": 1,
  "frequency_penalty": 0.0,
  "presence_penalty": 0.6
}

**Comment by 869413421** [comment]
那种方式运行的？

**Comment by 869413421** [comment]
> linux centos上。配置文件如下： { "api_key": "st-xxxxxxx", "port": 8081, "bot_desc": "You are an AI bot who will answer all my questions.", "proxy": "", "model": "gpt-3.5-turbo-0301", "max_tokens": 512, "temperature": 0.9, "top_p": 1, "frequency_penalty": 0.0, "presence_penalty": 0.6 }

那种方式运行的？

**Comment by yangyanghoho** [comment]
> > linux centos上。配置文件如下： { "api_key": "st-xxxxxxx", "port": 8081, "bot_desc": "You are an AI bot who will answer all my questions.", "proxy": "", "model": "gpt-3.5-turbo-0301", "max_tokens": 512, "temperature": 0.9, "top_p": 1, "frequency_penalty": 0.0, "presence_penalty": 0.6 }
> 
> 那种方式运行的？

Linux 本地解压运行的

# linux
$ tar xf chatgpt-xxxx.tar.gz # 解压
$ cd chatgpt-xxxx
$ cp config.dev.json config.json # 根据情况调整配置文件内容
$ vi config.json
$ ./chatgpt-web  # 直接运行

**Comment by 869413421** [comment]
> 

1.确保配置文件和二进制在同一目录下
2.确保key可用
3.确保环境下是否有APIKEY这个环境变量，如果有会优先读取APIKEY这个环境变量

**Comment by yangyanghoho** [comment]
> > 
> 
> 1.确保配置文件和二进制在同一目录下 2.确保key可用 3.确保环境下是否有APIKEY这个环境变量，如果有会优先读取APIKEY这个环境变量

前两条都满足
第三条 环境里没有APIKEY这个环境变量

尝试把key写环境变量里，结果一样的。

谢谢

**Comment by 869413421** [comment]
> > > 
> > 
> > 1.确保配置文件和二进制在同一目录下 2.确保key可用 3.确保环境下是否有APIKEY这个环境变量，如果有会优先读取APIKEY这个环境变量
> 
> 前两条都满足
> 第三条 环境里没有APIKEY这个环境变量
> 
> 尝试把key写环境变量里，结果一样的。
> 
> 谢谢

修改后有重新启动吗？提示信息显示是key认证失败了。
