### ISSUE TITLE
docker使用user 和password配置后好像没有效果

### ISSUE THREAD

**Issue by yangbinmao** [869413421/chatgpt-web#54]
如题：docker使用user 和password配置后好像没有效果。我使用了您提供的两种docker部署方式，但是均无效。我的无效是指，没有任何地方让我来输入使用的账号或密码。谢谢

**Comment by 869413421** [comment]
> 如题：docker使用user 和password配置后好像没有效果。我使用了您提供的两种docker部署方式，但是均无效。我的无效是指，没有任何地方让我来输入使用的账号或密码。谢谢

已经修复，请拉取最新镜像。
