### ISSUE TITLE
有百度广告链接

### ISSUE THREAD

**Issue by yangbinmao** [869413421/chatgpt-web#56]
![image](https://user-images.githubusercontent.com/44470220/223639521-b1d31bd0-5f01-4d35-9394-af619d2bd1e4.png)
既然本身没有访问调取成功，能不能把这个直接干掉。

**Comment by 869413421** [comment]
> ![image](https://user-images.githubusercontent.com/44470220/223639521-b1d31bd0-5f01-4d35-9394-af619d2bd1e4.png) 既然本身没有访问调取成功，能不能把这个直接干掉。

应该是你本机浏览器的问题，并没有在项目中植入广告连接。
