### ISSUE TITLE
docker-compose 运行后代理无法连接

### ISSUE THREAD

**Issue by linxchou** [869413421/chatgpt-web#58]
<img width="1211" alt="截屏2023-03-08 21 26 03" src="https://user-images.githubusercontent.com/66515124/223724945-4edb3ba5-87ad-4362-8ee7-abe4544456b7.png">

**Comment by 869413421** [comment]
> 
> <img width="1211" alt="截屏2023-03-08 21 26 03" src="https://user-images.githubusercontent.com/66515124/223724945-4edb3ba5-87ad-4362-8ee7-abe4544456b7.png">
> 

代理配置了127.0.0.1

**Comment by 869413421** [comment]
提供一下你docker-compose参数
