### ISSUE TITLE
request error

### ISSUE THREAD

**Issue by leexuan** [869413421/chatgpt-web#59]
宿主机配置代理ok后，chatgpt-web界面输入后，请求出错:
   请求出错，Post "https://api.openai.com/v1/chat/completions":dial tcp xx.xx.xx.xx:443: i/o timeout

这个错处是openai api不可用吗？

**Comment by frankyzhu76** [comment]
感觉是你的网络没有翻墙

**Comment by 869413421** [comment]
请正确配置代理后访问。

**Comment by leexuan** [comment]
代理应该是配置成功了，宿主机上使用curl -x proxy可以正常google等网站
