### ISSUE TITLE
内置代理无法使用

### ISSUE THREAD

**Issue by 214889191** [869413421/chatgpt-web#62]
2023年03月09日09:31:55
似乎内置代理无法回复数据,发起问题后一直处于等待状态

**Comment by 869413421** [comment]
> 2023年03月09日09:31:55
> 似乎内置代理无法回复数据,发起问题后一直处于等待状态

并没有内置代理，需要你自己提供代理后配置到项目中。

**Comment by 214889191** [comment]
Thank you for your reply and guidance
