### ISSUE TITLE
打开了exe文件，AI助手给不出我的问题答案，一直在加载中，config.json里的key也有改。

### ISSUE THREAD

**Issue by potatodontchop** [869413421/chatgpt-web#63]
水的化学式是什么。}
][GIN] 2023/03/09  11:34:17 500  21.0027881s::1POST"/completion"
命令行报500错误

**Comment by 869413421** [comment]
> 水的化学式是什么。}
> ][GIN] 2023/03/09  11:34:17 500  21.0027881s::1POST"/completion"
> 命令行报500错误

请配置代理
