### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by faith632011957** [869413421/chatgpt-web#65]
前端报错：Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by flybird119** [comment]
同样的错误，chrome浏览器

**Comment by q1285514609** [comment]
同样的错误，edge 火狐浏览器

**Comment by 869413421** [comment]
可以暂时参考[is40]( https://github.com/869413421/chatgpt-web/issues/40) 这个解决方法，服务端暂时没解决。

**Comment by 869413421** [comment]
已经尝试修复，指定了响应的js类型。请使用最新版本测试
