### ISSUE TITLE
几个建议~

### ISSUE THREAD

**Issue by frankyzhu76** [869413421/chatgpt-web#69]
1.配置文件尽量简单，优先考虑能访问，然后增加一个前端网页，各种参数放在前端读取和设置~这样对新手会友好很多~
2.手机端页面，打字的时候输入法会挡住问答
3.建议增加日志，其实对话的内容都在日志里，想办法也是能看的，不过前端如果能集成一下会更友好~

**Comment by 869413421** [comment]
1.这个项目在gpt3就已经诞生了，要兼容API，配置上来说都有默认值相对简单了。
2.已经修复
3.在后续计划中
