### ISSUE TITLE
为什么用过之后API被禁用了

### ISSUE THREAD

**Issue by EzrinL** [869413421/chatgpt-web#71]
为啥运行了这个项目之后，chatgpt就发邮件给我说我API被ban了。之后再用就不行。
我就正常的问答。什么都没违反。
你们出现过这种情况没。

使用报错：
请求出错，error.status code:429,message: Your accesswas terminated due toviolation of our policiesplease check your email formore information. lf youbelieve this is in errof andwould like to appeal, pleasecontactsupport@openai.com.

邮件：
After a thorough investigation, we have determined that you or a member of your organization are using the OpenAI API in ways that violate our policies.
Due to this breach we are halting access to the API immediately for the organization Personal. Common reasons for breach include violations of our content policy, repeated attempts at disallowed use-cases, or accessing the API from an unsupported location. You may also wish to review our Terms of Use.
If you believe this is in error and would like to appeal, please contact us through our help center. We will review appeals within one business day and will contact you if we reinstate access to the API.
Best,
The OpenAI team

**Comment by 3500024137** [comment]
你是不是经常换梯子

**Comment by frankyzhu76** [comment]
应该是从不允许的IP段，黑名单的IP段访问了API吧~

**Comment by 869413421** [comment]
最近openai大规模封禁，具体原因无从猜测。批量注册，频繁更换ip都有涉及。

**Comment by EzrinL** [comment]
> 

我肯定开代理访问啊，国内哪能访问
