### ISSUE TITLE
proxy具体怎么使用

### ISSUE THREAD

**Issue by haohaoxue** [869413421/chatgpt-web#76]
Clash开全局也没办法调用，一直报错
![123](https://user-images.githubusercontent.com/16409425/224768635-1d8f42bc-40d2-4d42-8311-0ce5650b8ec6.png)

**Comment by lwhdev** [comment]
配置文件config.json可以设置代理的,你再看看作者的文档

**Comment by haohaoxue** [comment]
> 配置文件config.json可以设置代理的,你再看看作者的文档

现在是浏览器访问没问题，就是程序访问不到接口，这个代理该怎么设置，或者是不是其他问题

**Comment by lwhdev** [comment]
嗯,要么是你配置文件代理没有配置好,比如我的是"proxy": "socks5://127.0.0.1:10808",如果配置对了,那可能是你的代理不行

**Comment by bitten-littlesuqirrel** [comment]
> 

我也是这个问题，请问您解决了吗

**Comment by loliuy** [comment]
加一，Clash也没效果

**Comment by hhhh124hhhh** [comment]
同样clash无效果

**Comment by lwhdev** [comment]
测试一下节点是否可选，这个测试非常简单。只需要直接通过浏览器打开链接 https://api.openai.com/v1，就可以轻松查看是否有响应

**Comment by 1548971643** [comment]
> Clash开全局也没办法调用，一直报错 ![123](https://user-images.githubusercontent.com/16409425/224768635-1d8f42bc-40d2-4d42-8311-0ce5650b8ec6.png)

是不是美国服务器部署就不需要配proxy呀
