### ISSUE TITLE
能在Docker镜像能增加一个ArmV8的Tag吗，无法拉取镜像，谢谢了！

### ISSUE THREAD

**Issue by sechina** [869413421/chatgpt-web#77]
能在Docker镜像能增加一个ArmV8的Tag吗，无法拉取镜像，谢谢了！

latest: Pulling from qingshui869413421/chatgpt-web
docker: no matching manifest for linux/arm/v8 in the manifest list entries.

**Comment by 869413421** [comment]
尝试将上面命令换成你对应的平台

**Comment by 869413421** [comment]
可以用项目中提供的dockerfile自己编译一份

**Comment by sechina** [comment]
> 可以用项目中提供的dockerfile自己编译一份

好的，我试试，多谢！
