### ISSUE TITLE
返回的格式，能格式化下吗

### ISSUE THREAD

**Issue by gygy** [869413421/chatgpt-web#8]
代码部分没有分行，都一起了
![SmartSelect_20230215_125034_Edge](https://user-images.githubusercontent.com/2096830/218934390-2b4aa6d6-9d5c-4535-b662-e8004b95c0f0.jpg)

**Comment by 869413421** [comment]
> 代码部分没有分行，都一起了
> ![SmartSelect_20230215_125034_Edge](https://user-images.githubusercontent.com/2096830/218934390-2b4aa6d6-9d5c-4535-b662-e8004b95c0f0.jpg)
> 

如果返回的文本中带了markdown的代码块语法是能正常显示的，但如果没有的话要强行优化他的显示需要实现一些复杂的前端逻辑。我暂时没有时间去实现

**Comment by 869413421** [comment]
> 代码部分没有分行，都一起了
> ![SmartSelect_20230215_125034_Edge](https://user-images.githubusercontent.com/2096830/218934390-2b4aa6d6-9d5c-4535-b662-e8004b95c0f0.jpg)
> 

请使用使用v0.0.2版本测试。
