### ISSUE TITLE
docker config部署后无响应

### ISSUE THREAD

**Issue by kaiyujiang** [869413421/chatgpt-web#89]
容器内部run.log如下
 [INFO]2023/03/22 09:03:29 logger.go:21: { [{user klpokpo。}]}
[INFO]2023/03/22 09:03:29 logger.go:21: [{system 你是一个AI聊天助手,，我需要你模拟一名温柔贴心的女朋友来回答我的问题。} {user klpokpo。}]
[GIN] 2023/03/22 - 09:03:29 | 500 |    3.375159ms |      172.17.0.1 | POST     "/completion"
![image](https://user-images.githubusercontent.com/109064748/226854154-43d9e0bb-c305-462b-984a-e1a1907e07ee.png)

config文件如下
  "api_url": "",
  "port": 8080,
  "listen": "",
  "bot_desc": "你是一个AI聊天助手,，我需要你模拟一名温柔贴心的女朋友来回答我的问题。",
  "proxy": "https://host.docker.internal:7890",
  "model": "gpt-3.5-turbo-0301",
  "max_tokens": 512,
  "temperature": 0.6,
  "top_p": 1,
  "frequency_penalty": 0.0,
  "presence_penalty": 0.6,
  "auth_user": "",
  "auth_password": ""

容器外面curl google.com 可以正常返回内容

网页上输入个词后会闪过下面的提示
请求出错，Post
"https://api.openai.com/vl/chat/co 
mpletions": proxyconnect tcp: dial 
top: lookup nost.docker.intemal 
on 183.60.83.19:53: no such host

不知道是哪里有问题？

**Comment by yylu1** [comment]
如果你容器的宿主机已经能够科学，把proxy那一行删掉就行了，这句是给没有科学的容器用于代理的，使用它首先要搭建了一个http代理或者socks5代理服务器，并把IP和端口改为代理服务器的IP和端口

**Comment by 869413421** [comment]
> 如果你容器的宿主机已经能够科学，把proxy那一行删掉就行了，这句是给没有科学的容器用于代理的，使用它首先要搭建了一个http代理或者socks5代理服务器，并把IP和端口改为代理服务器的IP和端口

正解，我要关闭这个问题了。
