### ISSUE TITLE
使用nginx反代通过域名访问时，无法正确渲染markdown

### ISSUE THREAD

**Issue by foryoung365** [869413421/chatgpt-web#90]
使用域名：
![image](https://user-images.githubusercontent.com/1758359/226950623-d5afdc5f-ae97-4a2a-8049-ddf24c4adf31.png)
使用IP直接访问则正常：
![image](https://user-images.githubusercontent.com/1758359/226950836-ad7f0c41-002d-4e87-b514-0ddf8285519a.png)

**Comment by 869413421** [comment]
已经修复。
