### ISSUE TITLE
好像不支持在回答中展示图片？不支持 markdown 吗？

### ISSUE THREAD

**Issue by finalrose7** [869413421/chatgpt-web#93]
如题，还是需要在哪配置呢？

**Comment by 869413421** [comment]
支持的，只要chatgpt响应的图片格式正确就能正常显示。

**Comment by finalrose7** [comment]
这种图片格式是正常的，但是没办法显示：
![324152450](https://user-images.githubusercontent.com/38653020/227674776-0e27303f-7ae0-4521-897c-85f5ed3b1a14.png)

**Comment by finalrose7** [comment]
> 这种图片格式是正常的，但是没办法显示： ![324152450](https://user-images.githubusercontent.com/38653020/227674776-0e27303f-7ae0-4521-897c-85f5ed3b1a14.png)

@869413421

**Comment by 869413421** [comment]
> > 这种图片格式是正常的，但是没办法显示： ![324152450](https://user-images.githubusercontent.com/38653020/227674776-0e27303f-7ae0-4521-897c-85f5ed3b1a14.png)
> 
> @869413421 

这应该是一个前端判断的问题，后续会修复。
