### ISSUE TITLE
页面空白啥也没有

### ISSUE THREAD

**Issue by zhangzq** [869413421/chatgpt-web#95]
查看console出现一个js错误：POST http://localhost:8080/auth/info net::ERR_CONNECTION_REFUSED。

然后如果部署了域名，也是 post 到localhost。

**Comment by 869413421** [comment]
提供下你运行的平台已经其他信息

**Comment by PorygonCN** [comment]
我也遇到了相同的问题 
部署方式是
使用readme文档提供的命令docker run的容器 
然后服务器通过反向代理  
```
location ~ {
    proxy_pass http://127.0.0.1:8080;
}
```

**Comment by wzr140803** [comment]
我是ubuntu21部署  也是空白

**Comment by 869413421** [comment]
> 查看console出现一个js错误：POST http://localhost:8080/auth/info net::ERR_CONNECTION_REFUSED。
> 
> 然后如果部署了域名，也是 post 到localhost。

控制台有错误信息吗

**Comment by wzr140803** [comment]
我也遇到这个问题了
Request URL: http://localhost:8080/auth/info
Request Method: POST
Status Code: 404 Not Found
Referrer Policy: strict-origin-when-cross-origin

**Comment by wzr140803** [comment]
部署在云服务器

**Comment by PorygonCN** [comment]
![image](https://user-images.githubusercontent.com/31176914/227927222-8af0b485-cfe3-4168-a40b-c7a85c68ed2a.png)
![image](https://user-images.githubusercontent.com/31176914/227927301-d00cce0e-3992-41ba-8885-dd3276f4c31a.png)

**Comment by 869413421** [comment]
应该是前端兼容性的问题，我尝试复现修复。

**Comment by hceasy** [comment]
![图片](https://user-images.githubusercontent.com/4436382/227931117-f42f2816-bd1b-4511-9611-09ec0259925f.png)
前端页面里哪句请求写成静态了?

**Comment by lxy1992** [comment]
@869413421 错误信息和 @hceasy 截图的是一样的

**Comment by 3038922** [comment]
我也是

**Comment by zhangzq** [comment]
> 提供下你运行的平台以及其他信息

本地windows/ubuntu subsystem部署、ubuntu云服务器部署都不行。上面很多人反馈了同样信息，我遇到的问题也是一样的。

**Comment by lxy1992** [comment]
@869413421 我想应该是某一个版本引入的问题，在修复前，可以告知下载哪个版本是可用的吗？

**Comment by hceasy** [comment]
临时解决方案 
将/assets/index-74d55ae0.js 中两个localhost  替换为自己的域名,可正常访问.

**Comment by 869413421** [comment]
已经修复，打包时不谨慎没注释调试参数，直接发布出去。请使用最新镜像和发布版本。

**Comment by 869413421** [comment]
> @869413421 我想应该是某一个版本引入的问题，在修复前，可以告知下载哪个版本是可用的吗？

修复了，用最新的可以了。

**Comment by lxy1992** [comment]
> > @869413421 我想应该是某一个版本引入的问题，在修复前，可以告知下载哪个版本是可用的吗？
> 
> 修复了，用最新的可以了。

@869413421 

还有两个小问题，但我已经想办法绕过并启动了，作者如果有空的话可以修复一下。除了这个，还有个需要看看的问题。

1. 现在的后续的auth info地址虽然不再使用localhost地址了，但是应该是读了本地绑定的域名，但如果我把这个服务绑定在域名后的/web endpoint后面，后续的调用依旧会错误。所以我现在先运行在根路径下。
2. 关于同时使用nginx和 chatgpt-web的朋友，作者很贴心的给了一个配置，这个配置里介绍了使用nginx自带的密码保护这个路径的方法，这个功能其实和服务本身的登录功能上重复了，而且配置后会导致循环的请求鉴权，不如直接去掉。

下面是一个关键的问题
3. 我登录后，开始聊天，但是一直不返回。我看了下docker log，没什么日志，不知道是出了什么问题，我测试了一下在这台机器上使用这个token访问是没问题的。

最后感谢作者的辛勤贡献，感谢！

**Comment by 869413421** [comment]
> > > @869413421 我想应该是某一个版本引入的问题，在修复前，可以告知下载哪个版本是可用的吗？
> > 
> > 
> > 修复了，用最新的可以了。
> 
> @869413421
> 
> 还有两个小问题，但我已经想办法绕过并启动了，作者如果有空的话可以修复一下。除了这个，还有个需要看看的问题。
> 
> 1. 现在的后续的auth info地址虽然不再使用localhost地址了，但是应该是读了本地绑定的域名，但如果我把这个服务绑定在域名后的/web endpoint后面，后续的调用依旧会错误。所以我现在先运行在根路径下。
> 2. 关于同时使用nginx和 chatgpt-web的朋友，作者很贴心的给了一个配置，这个配置里介绍了使用nginx自带的密码保护这个路径的方法，这个功能其实和服务本身的登录功能上重复了，而且配置后会导致循环的请求鉴权，不如直接去掉。
> 
> 下面是一个关键的问题 3. 我登录后，开始聊天，但是一直不返回。我看了下docker log，没什么日志，不知道是出了什么问题，我测试了一下在这台机器上使用这个token访问是没问题的。
> 
> 最后感谢作者的辛勤贡献，感谢！

docker使用了supervisord管理进程，日志输出在容器内的run.log。

**Comment by lxy1992** [comment]
> > > > @869413421 我想应该是某一个版本引入的问题，在修复前，可以告知下载哪个版本是可用的吗？
> > > 
> > > 
> > > 修复了，用最新的可以了。
> > 
> > 
> > @869413421
> > 还有两个小问题，但我已经想办法绕过并启动了，作者如果有空的话可以修复一下。除了这个，还有个需要看看的问题。
> > 
> > 1. 现在的后续的auth info地址虽然不再使用localhost地址了，但是应该是读了本地绑定的域名，但如果我把这个服务绑定在域名后的/web endpoint后面，后续的调用依旧会错误。所以我现在先运行在根路径下。
> > 2. 关于同时使用nginx和 chatgpt-web的朋友，作者很贴心的给了一个配置，这个配置里介绍了使用nginx自带的密码保护这个路径的方法，这个功能其实和服务本身的登录功能上重复了，而且配置后会导致循环的请求鉴权，不如直接去掉。
> > 
> > 下面是一个关键的问题 3. 我登录后，开始聊天，但是一直不返回。我看了下docker log，没什么日志，不知道是出了什么问题，我测试了一下在这台机器上使用这个token访问是没问题的。
> > 最后感谢作者的辛勤贡献，感谢！
> 
> docker使用了supervisord管理进程，日志输出在容器内的run.log。

@869413421 
你好， 我进容器找到了run.log，里面有一些access log, 但没有request log，没找到什么有用的信息。
我打开浏览器的console后，看到了报错，看起来，这个网页并没有去调用api，而是用的chat.openai.com/compeletion，使用的是网页版本的chatgpt，而不是项目文档中说的接口。感觉要么是机制不是用api，而是网页，要么就是根域名写错了。
我尝试修改了配置中的api访问地址，到可以使用的接口域名，但没有作用，这个页面依旧是去访问网页版本的chatgpt,而不是接口。
报错信息如下：

![CleanShot 2023-03-29 at 11 27 16](https://user-images.githubusercontent.com/6184994/228420066-bb3f2b94-927a-464f-8c09-21c051fdabc2.png)

**Comment by 869413421** [comment]
> > > > > @869413421 我想应该是某一个版本引入的问题，在修复前，可以告知下载哪个版本是可用的吗？
> > > > 
> > > > 
> > > > 修复了，用最新的可以了。
> > > 
> > > 
> > > @869413421
> > > 还有两个小问题，但我已经想办法绕过并启动了，作者如果有空的话可以修复一下。除了这个，还有个需要看看的问题。
> > > 
> > > 1. 现在的后续的auth info地址虽然不再使用localhost地址了，但是应该是读了本地绑定的域名，但如果我把这个服务绑定在域名后的/web endpoint后面，后续的调用依旧会错误。所以我现在先运行在根路径下。
> > > 2. 关于同时使用nginx和 chatgpt-web的朋友，作者很贴心的给了一个配置，这个配置里介绍了使用nginx自带的密码保护这个路径的方法，这个功能其实和服务本身的登录功能上重复了，而且配置后会导致循环的请求鉴权，不如直接去掉。
> > > 
> > > 下面是一个关键的问题 3. 我登录后，开始聊天，但是一直不返回。我看了下docker log，没什么日志，不知道是出了什么问题，我测试了一下在这台机器上使用这个token访问是没问题的。
> > > 最后感谢作者的辛勤贡献，感谢！
> > 
> > docker使用了supervisord管理进程，日志输出在容器内的run.log。
> 
> @869413421 
> 你好， 我进容器找到了run.log，里面有一些access log, 但没有request log，没找到什么有用的信息。
> 我打开浏览器的console后，看到了报错，看起来，这个网页并没有去调用api，而是用的chat.openai.com/compeletion，使用的是网页版本的chatgpt，而不是项目文档中说的接口。感觉要么是机制不是用api，而是网页，要么就是根域名写错了。
> 我尝试修改了配置中的api访问地址，到可以使用的接口域名，但没有作用，这个页面依旧是去访问网页版本的chatgpt,而不是接口。
> 报错信息如下：
> 
> ![CleanShot 2023-03-29 at 11 27 16](https://user-images.githubusercontent.com/6184994/228420066-bb3f2b94-927a-464f-8c09-21c051fdabc2.png)
> 

这个是项目的路由，根据你的图片中的信息接口返回了403。是因为登录信息过期导致的，尝试清空cookie操作。

**Comment by lxy1992** [comment]
> 

我的问题，是nginx配置的一个转发导致的，现在正常了，感谢！

**Comment by byronxu89** [comment]
求助，我现在也是这样的。 我的服务器配置较低，所以直接跑nginx 和 二进制文件，服务用IP 和端口访问没有问题， 用域名和反代出现错误。
![1680079363(1)](https://user-images.githubusercontent.com/14884494/228477998-f647e222-1818-4ba9-a134-7cc24cd0982c.png)
我的nginx 相关配置
![1680079427(1)](https://user-images.githubusercontent.com/14884494/228478263-00ed7d8e-77d6-47f7-a71f-c7ec43813d66.png)
