### ISSUE TITLE
AI之旅的账号密码是啥?

### ISSUE THREAD

**Issue by adairhmj** [869413421/chatgpt-web#96]
![image](https://user-images.githubusercontent.com/44510632/227891359-fd26f902-892f-449d-984c-1c8476e86380.png)
哪个大佬 帮忙说下.

**Comment by 869413421** [comment]
配置文件中的auth_user和auth_password,需要配置后才能使用。

**Comment by adairhmj** [comment]
呃，还是不太明白。具体是什么呢。

**Comment by adairhmj** [comment]
搞定了，谢谢老大、
