### ISSUE TITLE
一直卡这里,怎么回事呢,刷新也不行!

### ISSUE THREAD

**Issue by adairhmj** [869413421/chatgpt-web#98]
![image](https://user-images.githubusercontent.com/44510632/228131911-864ab40b-c3f5-415a-a41e-c62798040b44.png)

没有任何报错!

**Comment by 869413421** [comment]
openai没有响应，确保已经正确配置代理。

**Comment by kevinriver** [comment]
同样的问题，我设置了自己的api_url，这个api_url我在安卓客户端问天里试过了是可以的，但是这里不行，不知道怎么回事了。
请求网址: http://localhost:8383/chat/completion
请求方法: POST
状态代码: 500 Internal Server Error
远程地址: [::1]:8383
引荐来源网址政策: strict-origin-when-cross-origin

**Comment by kevinriver** [comment]
我搞定了，api_url这里填自己的域名后后面还得加/v1
比如：https://xxxx.com/v1
这样就可以了
